services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - .:/app
    depends_on:
      - cache

  cache:
    image: redis:alpine
